# Preprocessing
Cleaning the data using techniques discussed in class, including:
- Fixing incorrect formats
- Creating boolean representations for categorical variables
- Identifying extreme data values
- Identifying missing data
- Potentially imputing missing values from internal data
- Splitting one variable into multiple

In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv('data/0_raw_data/dataset.csv')
raw_data.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

# Fix Axis
The "unnamed" column should be the idx

In [3]:
raw_data = raw_data.set_index("Unnamed: 0")
raw_data.index.name = "idx"
raw_data.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
idx,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

# Missing Values

We are going to check for any missing values in the data

In [4]:
missing_values = raw_data.isnull().sum()
missing_values

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [5]:
rows_with_missing_values = raw_data[raw_data.isnull().any(axis=1)]
rows_with_missing_values

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
idx,,,,,,,,,,,,,,,,,,,,
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

Only this one entry has missing values. As such, it can be safely deleted.

In [6]:
# Delete row with index 65900
raw_data = raw_data.drop(index=65900)
missing_values = raw_data.isnull().sum()
missing_values

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

# Extreme Values
Analyze potentially extreme values to see if any adjustments are necessary

In [7]:
# Calculate extreme values for each column. Use the following format:
'''
#### Identify Extreme Data Values

# Importing necessary libraries
import pandas as pd

# Load the data
data = pd.read_csv('vote.csv')

# Calculate the 5th and 95th percentiles of age
age_5th_percentile = data['age'].quantile(0.05)
age_95th_percentile = data['age'].quantile(0.95)

# Get the range of the oldest 5% and youngest 5% of respondents
oldest_5_percent_range = data[data['age'] >= age_95th_percentile]['age'].agg(['min', 'max'])
youngest_5_percent_range = data[data['age'] <= age_5th_percentile]['age'].agg(['min', 'max'])

# Count the number of respondents above 100 and below 18
above_100_count = data[data['age'] > 100].shape[0]
below_18_count = data[data['age'] < 18].shape[0]

print('Highest age of the lowest 5%:', age_5th_percentile)
print('Lowest age of the highest 5%:', age_95th_percentile)
print('Oldest 5% age range:', oldest_5_percent_range)
print('Youngest 5% age range:', youngest_5_percent_range)
print('Number of respondents above 100:', above_100_count)
print('Number of respondents below 18:', below_18_count)
'''

numeric_columns = raw_data.select_dtypes(include='number').columns

for column in numeric_columns:
    # Calculate the 5th and 95th percentiles
    lower_bound = raw_data[column].quantile(0.05)
    upper_bound = raw_data[column].quantile(0.95)
    
    # Get the range of the lowest 5% and highest 5% of values
    lowest_5_percent_range = raw_data[raw_data[column] <= lower_bound][column].agg(['min', 'max'])
    highest_5_percent_range = raw_data[raw_data[column] >= upper_bound][column].agg(['min', 'max'])\
    
    # Calculate number of values above the upper bound and below the lower bound
    above_upper_bound_count = raw_data[raw_data[column] > upper_bound].shape[0]
    below_lower_bound_count = raw_data[raw_data[column] < lower_bound].shape[0]

    # Calculate the percentage of values above the upper bound and below the lower bound
    total_count = raw_data.shape[0]
    above_upper_bound_percentage = (above_upper_bound_count / total_count) * 100
    below_lower_bound_percentage = (below_lower_bound_count / total_count) * 100
    
    print(f'Column: {column}')
    print(f'Lowest 5% range: {lowest_5_percent_range}')
    print(f'Highest 5% range: {highest_5_percent_range}')
    print(f'Number of values above upper bound: {above_upper_bound_count}')
    print(f'Number of values below lower bound: {below_lower_bound_count}')
    print(f'Percentage of values above upper bound: {above_upper_bound_percentage:.2f}%')
    print(f'Percentage of values below lower bound: {below_lower_bound_percentage:.2f}%')

    print()

Column: popularity
Lowest 5% range: min    0
max    0
Name: popularity, dtype: int64
Highest 5% range: min     69
max    100
Name: popularity, dtype: int64
Number of values above upper bound: 5472
Number of values below lower bound: 0
Percentage of values above upper bound: 4.80%
Percentage of values below lower bound: 0.00%

Column: duration_ms
Lowest 5% range: min      8586
max    116920
Name: duration_ms, dtype: int64
Highest 5% range: min     387169
max    5237295
Name: duration_ms, dtype: int64
Number of values above upper bound: 5700
Number of values below lower bound: 5700
Percentage of values above upper bound: 5.00%
Percentage of values below lower bound: 5.00%

Column: danceability
Lowest 5% range: min    0.00
max    0.25
Name: danceability, dtype: float64
Highest 5% range: min    0.824
max    0.985
Name: danceability, dtype: float64
Number of values above upper bound: 5672
Number of values below lower bound: 5694
Percentage of values above upper bound: 4.98%
Percentage of values below lower bound: 4.99%

Column: energy
Lowest 5% range: min    0.000
max    0.154
Name: energy, dtype: float64
Highest 5% range: min    0.969
max    1.000
Name: energy, dtype: float64
Number of values above upper bound: 5542
Number of values below lower bound: 5679
Percentage of values above upper bound: 4.86%
Percentage of values below lower bound: 4.98%

Column: key
Lowest 5% range: min    0
max    0
Name: key, dtype: int64
Highest 5% range: min    11
max    11
Name: key, dtype: int64
Number of values above upper bound: 0
Number of values below lower bound: 0
Percentage of values above upper bound: 0.00%
Percentage of values below lower bound: 0.00%

Column: loudness
Lowest 5% range: min   -49.531
max   -18.067
Name: loudness, dtype: float64
Highest 5% range: min   -2.974
max    4.532
Name: loudness, dtype: float64
Number of values above upper bound: 5694
Number of values below lower bound: 5699
Percentage of values above upper bound: 4.99%
Percentage of values below lower bound: 5.00%

Column: mode
Lowest 5% range: min    0
max    0
Name: mode, dtype: int64
Highest 5% range: min    1
max    1
Name: mode, dtype: int64
Number of values above upper bound: 0
Number of values below lower bound: 0
Percentage of values above upper bound: 0.00%
Percentage of values below lower bound: 0.00%

Column: speechiness
Lowest 5% range: min    0.0000
max    0.0282
Name: speechiness, dtype: float64
Highest 5% range: min    0.268
max    0.965
Name: speechiness, dtype: float64
Number of values above upper bound: 5691
Number of values below lower bound: 5484
Percentage of values above upper bound: 4.99%
Percentage of values below lower bound: 4.81%

Column: acousticness
Lowest 5% range: min    0.000000
max    0.000145
Name: acousticness, dtype: float64
Highest 5% range: min    0.948
max    0.996
Name: acousticness, dtype: float64
Number of values above upper bound: 5657
Number of values below lower bound: 5687
Percentage of values above upper bound: 4.96%
Percentage of values below lower bound: 4.99%

Column: instrumentalness
Lowest 5% range: min    0.0
max    0.0
Name: instrumentalness, dtype: float64
Highest 5% range: min    0.904
max    1.000
Name: instrumentalness, dtype: float64
Number of values above upper bound: 5671
Number of values below lower bound: 0
Percentage of values above upper bound: 4.97%
Percentage of values below lower bound: 0.00%

Column: liveness
Lowest 5% range: min    0.0000
max    0.0606
Name: liveness, dtype: float64
Highest 5% range: min    0.681
max    1.000
Name: liveness, dtype: float64
Number of values above upper bound: 5682
Number of values below lower bound: 5691
Percentage of values above upper bound: 4.98%
Percentage of values below lower bound: 4.99%

Column: valence
Lowest 5% range: min    0.0000
max    0.0708
Name: valence, dtype: float64
Highest 5% range: min    0.911
max    0.995
Name: valence, dtype: float64
Number of values above upper bound: 5688
Number of values below lower bound: 5685
Percentage of values above upper bound: 4.99%
Percentage of values below lower bound: 4.99%

Column: tempo
Lowest 5% range: min     0.000
max    77.345
Name: tempo, dtype: float64
Highest 5% range: min    175.070
max    243.372
Name: tempo, dtype: float64
Number of values above upper bound: 5700
Number of values below lower bound: 5700
Percentage of values above upper bound: 5.00%
Percentage of values below lower bound: 5.00%

Column: time_signature
Lowest 5% range: min    0
max    3
Name: time_signature, dtype: int64
Highest 5% range: min    4
max    5
Name: time_signature, dtype: int64
Number of values above upper bound: 1826
Number of values below lower bound: 1136
Percentage of values above upper bound: 1.60%
Percentage of values below lower bound: 1.00%

# Store preprocessed data
No further action necessary, data was already mostly properly preprocessed and formatted!

In [8]:
raw_data.to_csv('data/1_preprocessed/preprocessed_dataset.csv')